/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2017-11-27 18:19:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import Justice.*;

public final class proces_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("Justice");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("<TITLE>IFT287 - Système de gestion d'un palais de justice</TITLE>\r\n");
      out.write("<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">\r\n");
      out.write("<META NAME=\"author\" CONTENT=\"Pierrick BOBET\">\r\n");
      out.write("<META NAME=\"author\" CONTENT=\"Rémy BOUTELOUP\">\r\n");
      out.write("<META NAME=\"description\"\r\n");
      out.write("CONTENT=\"Gestion des proces\">\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("<CENTER>\r\n");
      out.write("<H1>Système de gestion d'un palais de justice</H1>\r\n");
      out.write("<H2>Gestion des proces</H2> <br>\r\n");
      out.write("</CENTER>\r\n");
      out.write("\r\n");
      out.write("<br><a href=\"Proces?param=retour\">Retour</a><br>\r\n");
      out.write("\r\n");
      out.write("<H3>Création</H3>\r\n");
      out.write("\r\n");
	List<String> listeMessageErreur = new LinkedList<String>();
	Boolean erreur = false;
	
	GestionJustice justiceInterrogation = (GestionJustice) session.getAttribute("justiceInterrogation");
	ArrayList<TupleJuge> listJuge = justiceInterrogation.getGestionJuge().affichageAll();
	ArrayList<TuplePartie> listPartie = justiceInterrogation.getGestionPartie().retourneAll();

	if (listJuge.size() == 0)
	{
        listeMessageErreur.add("Création impossible : Aucun juge actif dans la base de données");
        request.setAttribute("listeMessageErreur", listeMessageErreur);
        erreur = true;
	}
	
	if (listPartie.size() == 0 || listPartie.size() == 1)
	{
		listeMessageErreur.add("Création impossible : La base de données doit contenir au moins deux parties");
        request.setAttribute("listeMessageErreur", listeMessageErreur);
        erreur = true;
	}

	if (!erreur)
	{ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<TABLE style=\"border: 1px solid #A4A4A4\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Id</td>\r\n");
      out.write("\t\t\t<td>Juge</td>\r\n");
      out.write("\t\t\t<td>Date</td>\r\n");
      out.write("\t\t\t<td>DevantJury</td>\r\n");
      out.write("\t\t\t<td>PartieDefenderesse</td>\r\n");
      out.write("\t\t\t<td>PartiePoursuivant</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<form action=\"Proces\" method=\"POST\">\r\n");
			if (request.getParameter("id") != null)
			{ 
      out.write("\r\n");
      out.write("\t\t\t\t<td> <input type=\"text\" name=\"id\" value='");
      out.print( request.getParameter("id") );
      out.write("' /> </td>\r\n");
      out.write("\t\t\t");
}
			else
			{ 
      out.write("\r\n");
      out.write("\t\t\t\t<td> <input type=\"text\" name=\"id\" value=\"\"/> </td>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td> <SELECT name=\"selectJuge\" size=\"1\">\r\n");
					for (int i = 0; i < listJuge.size(); i++)
					{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<OPTION> ");
      out.print( listJuge.get(i).getId() );
      out.write(" </OPTION>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</SELECT></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td> <input type=\"text\" name=\"date\" placeholder=\"2017/12/25\"/> </td>\r\n");
      out.write("\t\t\t<td> <SELECT name=\"selectDevantJury\" size=\"1\">\r\n");
      out.write("\t\t\t\t<OPTION>Vrai</OPTION>\r\n");
      out.write("\t\t\t\t<OPTION>Faux</OPTION>\r\n");
      out.write("\t\t\t</SELECT></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td> <SELECT name=\"selectPartieD\" size=\"1\">\r\n");
					for (int i = 0; i < listPartie.size(); i++)
					{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<OPTION> ");
      out.print( listPartie.get(i).getId() );
      out.write(" </OPTION>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</SELECT></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td> <SELECT name=\"selectPartieP\" size=\"1\">\r\n");
					for (int i = 0; i < listPartie.size(); i++)
					{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<OPTION> ");
      out.print( listPartie.get(i).getId() );
      out.write(" </OPTION>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</SELECT></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"Valider\" value=\"Ajouter\"></td>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<H3>Terminer un proces</H3>\r\n");
      out.write("<form action=\"Proces\" method=\"POST\">\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\t<label for=\"IdATerminer\">Id du proces à terminer : </label>\r\n");
      out.write("\t\t<SELECT name=\"IdATerminer\" size=\"1\">\r\n");

	ArrayList<TupleProces> list = justiceInterrogation.getGestionProces().retourneAllNonTermine();

	for (int i = 0; i < list.size(); i++)
	{

      out.write("\r\n");
      out.write("\t<OPTION> ");
      out.print( list.get(i).getId() );
      out.write(" </OPTION>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t</SELECT>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p> <label for=\"Decision\">Decision :</label>\r\n");
      out.write("  \t\t<SELECT name=\"Decision\" size=\"1\"> \r\n");
      out.write("  \t\t\t<OPTION>Poursuite gagne</OPTION>\r\n");
      out.write("  \t\t\t<OPTION>Poursuite perd</OPTION>\r\n");
      out.write("  \t\t</SELECT>\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"submit\" name=\"Terminer\" value=\"Terminer\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<H3>Affichage de l'ensemble des proces</H3>\r\n");
      out.write("\t");
list = justiceInterrogation.getGestionProces().retourneAll();
      out.write("\r\n");
      out.write("<form action=\"Proces\" method=\"POST\">\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\t<TABLE BORDER=1 WIDTH=600>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TH>Identifiant</TH>\r\n");
      out.write("\t\t\t\t<TH>Juge</TH>\r\n");
      out.write("\t\t\t\t<TH>Date</TH>\r\n");
      out.write("\t\t\t\t<TH>DevantJury</TH>\r\n");
      out.write("\t\t\t\t<TH>PartieDefenderesse</TH>\r\n");
      out.write("\t\t\t\t<TH>PartiePoursuivante</TH>\r\n");
      out.write("\t\t\t\t<TH>Decision</TH>\r\n");
      out.write("\t\t\t");

			for (int i = 0 ; i < list.size(); i++)
			{ 
      out.write("\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD>");
      out.print( list.get(i).getId() );
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD>");
      out.print( list.get(i).getJuge_id() );
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD>");
      out.print( list.get(i).getDate().toString() );
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD>");
      out.print( list.get(i).getDevantJury() );
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD>");
      out.print( list.get(i).getPartieDefenderesse_id() );
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD>");
      out.print( list.get(i).getPartiePoursuivant_id() );
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD>");
      out.print( list.get(i).getDecision() );
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("\t</p>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/messageErreur.jsp", out, false);
      out.write("\r\n");
      out.write("<BR>\r\n");
      out.write("<a href=\"Logout\">Sortir</a>\r\n");
      out.write("<BR>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("Date et heure normale de l'est: ");
      out.print( DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, Locale.CANADA_FRENCH).format(new java.util.Date()) );
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
