-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 14:42:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema postgres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema postgres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table "Juge"
-- -----------------------------------------------------
CREATE TABLE  "Juge" (
  "id" INT UNIQUE,
  "prenom" VARCHAR(45) NOT NULL,
  "nom" VARCHAR(45) NOT NULL,
  "age" INT NOT NULL,
  "disponible" BOOLEAN NOT NULL DEFAULT true,
  "quitterJustice" BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "Avocat"
-- -----------------------------------------------------
CREATE TABLE  "Avocat" (
  "id" INT UNIQUE,
  "prenom" VARCHAR(45) NOT NULL,
  "nom" VARCHAR(45) NOT NULL,
  "type" INT NOT NULL,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "Partie"
-- -----------------------------------------------------
CREATE TABLE  "Partie" (
  "id" INT UNIQUE,
  "prenom" VARCHAR(45) NOT NULL,
  "nom" VARCHAR(45) NOT NULL,
  "Avocat_id" INT NOT NULL,
  PRIMARY KEY ("id", "Avocat_id"),
  CONSTRAINT "fk_Partie_Avocat"
    FOREIGN KEY ("Avocat_id")
    REFERENCES "Avocat" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "Proces"
-- -----------------------------------------------------
CREATE TABLE  "Proces" (
  "id" INT UNIQUE,
  "Juge_id" INT NOT NULL,
  "date" TIMESTAMP NOT NULL,
  "devantJury" INT NOT NULL,
  "PartieDefenderesse_id" INT NOT NULL,
  "PartiePoursuivant_id" INT NOT NULL,
  "decision" INT NULL,
  PRIMARY KEY ("id", "Juge_id", "PartieDefenderesse_id", "PartiePoursuivant_id"),
  CONSTRAINT "fk_Procès_Juge1"
    FOREIGN KEY ("Juge_id")
    REFERENCES "Juge" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Procès_Partie defenderesse1"
    FOREIGN KEY ("PartieDefenderesse_id")
    REFERENCES "Partie" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Procès_Partie1"
    FOREIGN KEY ("PartiePoursuivant_id")
    REFERENCES "Partie" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "Seance"
-- -----------------------------------------------------
CREATE TABLE  "Seance" (
  "id" INT UNIQUE,
  "Proces_id" INT NOT NULL,
  "date" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id", "Proces_id"),
  CONSTRAINT "fk_Seance_Procès1"
    FOREIGN KEY ("Proces_id")
    REFERENCES "Proces" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "Jury"
-- -----------------------------------------------------
CREATE TABLE  "Jury" (
  "nas" INT UNIQUE,
  "prenom" VARCHAR(45) NULL,
  "nom" VARCHAR(45) NULL,
  "sexe" VARCHAR(1) NOT NULL,
  "age" INT NOT NULL,
  "occupe" BOOLEAN NOT NULL,
  PRIMARY KEY ("nas"));

  -- -----------------------------------------------------
  -- Table "JuryProces"
  -- -----------------------------------------------------
CREATE TABLE "JuryProces" (
  "Jury_id" integer,
  "Proces_id" integer,
  CONSTRAINT "JuryProces_pkey" PRIMARY KEY ("Jury_id", "Proces_id"),
  CONSTRAINT "fk_Proces" FOREIGN KEY ("Proces_id")
      REFERENCES "Proces" (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_Jury" FOREIGN KEY ("Jury_id")
      REFERENCES "Jury" (nas) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION);
